Repository FuelLabs/swayswap, pull requests merged in 2022-05, with the labels that each got.

#60 Add `README.md` to the project
  README.md
  cover.png
Labels: documentation

#71 chore: comment empty sections on readme
  README.md
Labels: documentation

#58 Add Swaps
  .github/workflows/gh-pages.yml
  client/deploy-contracts/index.ts
  client/package.json
  client/src/components/CoinInput.tsx
  client/src/config.ts
  client/src/context/WalletContext.tsx
  client/src/lib/CoinsMetadata.ts
  client/src/pages/MintToken.tsx
  client/src/pages/Pool.tsx
  client/src/pages/RemoveLiquidity.tsx
  client/src/pages/Swap.tsx
  client/src/types/contracts/SwayswapContractAbi.d.ts
  client/src/types/contracts/factories/SwayswapContractAbi__factory.ts
  client/yarn.lock
  contracts/swayswap_abi/Forc.lock
  contracts/swayswap_abi/src/main.sw
  contracts/swayswap_contract/src/main.sw
Labels: enhancement

#81 fix: swap get values
  .github/workflows/gh-pages.yml
  client/deploy-contracts/index.ts
  client/package.json
  client/src/components/CoinInput.tsx
  client/src/config.ts
  client/src/pages/MintTokenPage.tsx
  client/src/pages/PoolPage.tsx
  client/src/pages/RemoveLiquidityPage.tsx
  client/src/pages/SwapPage.tsx
  client/src/types/contracts/SwayswapContractAbi.d.ts
  client/src/types/contracts/TokenContractAbi.d.ts
  client/src/types/contracts/factories/SwayswapContractAbi__factory.ts
  client/yarn.lock
  contracts/swayswap_abi/src/main.sw
  contracts/swayswap_contract/Forc.lock
  contracts/swayswap_contract/src/main.sw
  contracts/token_contract/Forc.lock
  docker/fuel-core/Dockerfile
  docker/fuel-core/chainConfig.json
Labels: bug

#88 feat: track reserve amounts on storage
  client/package.json
  client/src/AppRoutes.tsx
  client/src/components/Header.tsx
  client/src/pages/MintTokenPage.tsx
  client/src/pages/PoolPage.tsx
  client/src/pages/RemoveLiquidityPage.tsx
  client/src/pages/SwapPage.tsx
  client/src/pages/WalletPage.tsx
  client/src/types/contracts/SwayswapContractAbi.d.ts
  client/src/types/contracts/factories/SwayswapContractAbi__factory.ts
  client/src/types/pages.ts
  client/yarn.lock
  contracts/swayswap_abi/src/main.sw
  contracts/swayswap_contract/src/main.sw
Labels: enhancement

#77 Add Support for the new Faucet
  client/.env.example
  client/package.json
  client/public/index.html
  client/src/AppRoutes.tsx
  client/src/config.ts
  client/src/pages/FaucetPage.tsx
  client/src/pages/SwapPage.tsx
  client/src/pages/WalletPage.tsx
  client/src/types/pages.ts
  client/yarn.lock
Labels: enhancement

#97 feat: improve coin input max and value validation
  client/src/components/CoinInput.tsx
  client/src/config.ts
  client/src/context/AppContext.tsx
Labels: enhancement

#99 refac: add animation on invert button
  client/src/components/InvertButton.tsx
Labels: enhancement

#100 refac: a lot of ui/ux improvements
  client/package.json
  client/src/App.tsx
  client/src/AppRoutes.tsx
  client/src/components/Button.tsx
  client/src/components/CoinInput.tsx
  client/src/components/CoinSelector.tsx
  client/src/components/Header.tsx
  client/src/components/InvertButton.tsx
  client/src/components/Link.tsx
  client/src/components/RequireWallet.tsx
  client/src/components/Spinner.tsx
  client/src/components/Toaster.tsx
  client/src/components/WalletCard.tsx
  client/src/hooks/useAssets.ts
  client/src/hooks/useFaucet.ts
  client/src/hooks/useTokensMethods.ts
  client/src/index.css
  client/src/index.tsx
  client/src/layouts/MainLayout.tsx
  client/src/pages/FaucetPage.tsx
  client/src/pages/MintTokenPage.tsx
  client/src/pages/PoolPage.tsx
  client/src/pages/RemoveLiquidityPage.tsx
  client/src/pages/SetupPage.tsx
  client/src/pages/SwapPage.tsx
  client/src/pages/WalletPage.tsx
  client/tailwind.config.js
  client/yarn.lock
Labels: enhancement

#102 feat: update swap page checks
  .github/workflows/gh-pages.yml
  client/src/components/AssetItem.tsx
  client/src/components/CoinInput.tsx
  client/src/hooks/useDebounce.tsx
  client/src/pages/PoolPage.tsx
  client/src/pages/RemoveLiquidityPage.tsx
  client/src/pages/SwapPage.tsx
  client/src/pages/SwapPage/SwapComponent.tsx
  client/src/pages/SwapPage/index.tsx
  client/src/pages/SwapPage/queries.ts
  client/src/pages/SwapPage/types.ts
  client/src/types/contracts/ExchangeContractAbi.d.ts
  client/src/types/contracts/SwayswapContractAbi.d.ts
  client/src/types/contracts/factories/ExchangeContractAbi__factory.ts
  client/src/types/contracts/factories/SwayswapContractAbi__factory.ts
  client/src/types/contracts/index.ts
  contracts/exchange_abi/src/main.sw
  contracts/exchange_contract/src/main.sw
  contracts/exchange_contract/tests/harness.rs
Labels: enhancement

#109 Fix from/to range calculations in pool page
  client/src/pages/PoolPage.tsx
Labels: bug, enhancement

#106 feat: add coin list modal and pool as sub-route
  client/.prettierrc
  client/package.json
  client/src/App.tsx
  client/src/AppRoutes.tsx
  client/src/components/AssetItem.tsx
  client/src/components/Button.tsx
  client/src/components/CoinInput.tsx
  client/src/components/CoinSelector.tsx
  client/src/components/CoinsListDialog.tsx
  client/src/components/Dialog.tsx
  client/src/components/Header.tsx
  client/src/components/Input.tsx
  client/src/components/InvertButton.tsx
  client/src/components/Menu.tsx
  client/src/components/NumberInput.tsx
  client/src/components/PageContent.tsx
  client/src/components/TextInput.tsx
  client/src/components/Toaster.tsx
  client/src/components/WalletCard.tsx
  client/src/hooks/useAssets.ts
  client/src/hooks/useBalances.ts
  client/src/index.css
  client/src/layouts/MainLayout.tsx
  client/src/lib/CoinsMetadata.ts
  client/src/pages/FaucetPage.tsx
  client/src/pages/MintTokenPage.tsx
  client/src/pages/PoolPage.tsx
  client/src/pages/PoolPage/AddLiquidity.tsx
  client/src/pages/PoolPage/RemoveLiquidity.tsx
  client/src/pages/PoolPage/index.tsx
  client/src/pages/SwapPage/SwapComponent.tsx
  client/src/pages/SwapPage/index.tsx
  client/src/types/index.ts
  client/src/types/pages.ts
  client/tailwind.config.js
  client/tsconfig.json
  client/yarn.lock
Labels: enhancement

#114 fix: update icons url
  client/src/components/CoinSelector.tsx
  client/src/components/CoinsListDialog.tsx
  client/src/hooks/useAssets.ts
Labels: bug

#115 fix: update icons url
  client/src/hooks/useAssets.ts
  client/src/lib/CoinsMetadata.ts
  client/src/lib/utils.ts
Labels: bug

#116 Check balance amount before swap
  client/src/components/CoinInput.tsx
  client/src/lib/utils.ts
  client/src/pages/SwapPage/index.tsx
Labels: bug, enhancement

#117 Save Swap Page global state
  client/package.json
  client/src/pages/SwapPage/SwapComponent.tsx
  client/src/pages/SwapPage/jotai.ts
  client/yarn.lock
Labels: enhancement

#143 style: change pool tabs style
  .github/workflows/gh-pages.yml
  packages/app/scripts/deploy-contracts.sh
  packages/app/src/components/PageContent.tsx
  packages/app/src/pages/PoolPage/index.tsx
Labels: enhancement, ui/ux

#152 fix: update contracts to forc to v0.13.0
  contracts/exchange_contract/Forc.lock
  contracts/exchange_contract/src/main.sw
  contracts/token_contract/Forc.lock
  package.json
  packages/app/deploy-contracts/index.ts
  packages/app/scripts/deploy-contracts.sh
  packages/app/src/types/contracts/ExchangeContractAbi.d.ts
  packages/app/src/types/contracts/SwayswapContractAbi.d.ts
  packages/app/src/types/contracts/TokenContractAbi.d.ts
  packages/app/src/types/contracts/common.d.ts
  packages/app/src/types/contracts/index.ts
Labels: bug, contracts

#153 feat: add mint inside dropdown menu on wallet card header
  packages/app/package.json
  packages/app/src/components/Button.tsx
  packages/app/src/components/CoinSelector.tsx
  packages/app/src/components/Dialog.tsx
  packages/app/src/components/Input.tsx
  packages/app/src/components/Menu.tsx
  packages/app/src/components/NumberInput.tsx
  packages/app/src/components/PageContent.tsx
  packages/app/src/components/Popover.tsx
  packages/app/src/components/Spinner.tsx
  packages/app/src/components/TextInput.tsx
  packages/app/src/components/WalletCard.tsx
  packages/app/src/pages/MintTokenPage.tsx
  pnpm-lock.yaml
Labels: feature

#157 feat: add price per token feature on swap
  packages/app/package.json
  packages/app/src/components/Button.tsx
  packages/app/src/components/CoinInput.tsx
  packages/app/src/components/NumberInput.tsx
  packages/app/src/components/Spinner.tsx
  packages/app/src/config.ts
  packages/app/src/pages/SwapPage/PricePerToken.tsx
  packages/app/src/pages/SwapPage/SwapComponent.tsx
  packages/app/src/pages/SwapPage/index.tsx
  packages/app/src/pages/SwapPage/jotai.ts
  pnpm-lock.yaml
Labels: feature

#166 refac: remove recoil and use jotai instead
  packages/app/package.json
  packages/app/src/App.tsx
  packages/app/src/context/AppContext.tsx
  packages/app/src/lib/recoilEffects.ts
  pnpm-lock.yaml
Labels: enhancement

#168 refac: add skeleton as loading
  packages/app/package.json
  packages/app/src/components/Skeleton.tsx
  packages/app/src/layouts/MainLayout.tsx
  pnpm-lock.yaml
Labels: enhancement, ui/ux

#172 chore: update build script to copy 404
  packages/app/package.json
Labels: bug, config

#164 feat: Save state of pool page
  packages/app/src/pages/PoolPage/AddLiquidity.tsx
  packages/app/src/pages/PoolPage/jotai.ts
Labels: enhancement, ui/ux

#185 feat(PoolPage): When set input value, calculate the other input value. Validate if pool ratio is right
  packages/app/src/components/CoinInput.tsx
  packages/app/src/config.ts
  packages/app/src/lib/asset.ts
  packages/app/src/pages/PoolPage/AddLiquidity.tsx
Labels: enhancement

#187 feat(PoolPage): improve button feedback. reload/clear after create liquidity
  packages/app/src/pages/PoolPage/AddLiquidity.tsx
Labels: enhancement, page:pools

#188 feat: add user guided states on swap
  packages/app/package.json
  packages/app/src/config.ts
  packages/app/src/lib/utils.ts
  packages/app/src/pages/SwapPage/PricePerToken.tsx
  packages/app/src/pages/SwapPage/SwapComponent.tsx
  packages/app/src/pages/SwapPage/index.tsx
  packages/app/src/pages/SwapPage/types.ts
  pnpm-lock.yaml
Labels: page:swap

#178 ci: add action for validate pull request
  .github/workflows/pr.yaml
  README.md
  packages/app/README.md
Labels: enhancement

#184 feat: add dropdown to select token on swap
  README.md
  packages/app/package.json
  packages/app/src/components/CoinSelector.tsx
  packages/app/src/components/CoinsListDialog.tsx
  packages/app/src/index.css
  packages/app/src/lib/asset.ts
  packages/app/src/pages/PoolPage/AddLiquidity.tsx
  packages/app/src/pages/PoolPage/jotai.ts
  packages/app/src/pages/SwapPage/PricePerToken.tsx
  packages/app/src/pages/SwapPage/SwapComponent.tsx
  packages/app/src/pages/SwapPage/index.tsx
  packages/app/src/pages/SwapPage/jotai.ts
Labels: feature

#199 feat: auto faucet
  packages/app/src/components/Toaster.tsx
  packages/app/src/components/WalletWidget.tsx
  packages/app/src/hooks/useFaucet.ts
  packages/app/src/hooks/useUserInfo.ts
  packages/app/src/pages/CreateWallet.tsx
Labels: ui/ux, feature

#196 feat(PoolPage): add feedback alert when creating a new pool
  packages/app/src/pages/PoolPage/AddLiquidity.tsx
Labels: enhancement

#201 fix(PoolPage): handle error feedback (getting stuck in Provide Liquidity stage)
  packages/app/src/pages/PoolPage/AddLiquidity.tsx
Labels: bug, enhancement

#194 feat(PoolPage): improve button feedback + improve success feedback
  packages/app/src/pages/PoolPage/RemoveLiquidity.tsx
Labels: enhancement

#171 chore: make use of any type an eslint error
  packages/app/deploy-contracts/index.ts
  packages/app/src/components/ButtonGroup.tsx
  packages/app/src/components/Card.tsx
  packages/app/src/components/CoinInput.tsx
  packages/app/src/components/Header.tsx
  packages/app/src/components/Menu.tsx
  packages/app/src/components/Popover.tsx
  packages/app/src/components/Tooltip.tsx
  packages/app/src/hooks/useBalances.ts
  packages/app/src/pages/PoolPage/AddLiquidity.tsx
  packages/config/eslint.js
  packages/test-utils/src/mocks/image.ts
  packages/test-utils/src/user-event.ts
Labels: config

#204 feat: implement Accordion component
  packages/app/package.json
  packages/app/postcss.config.js
  packages/app/src/components/Accordion.tsx
  packages/app/src/components/Dialog.tsx
  packages/app/src/main.tsx
  packages/app/src/styles/base.css
  packages/app/src/styles/components/accordion.css
  packages/app/src/styles/components/button.css
  packages/app/src/styles/components/coin-selector.css
  packages/app/src/styles/index.css
  packages/app/src/styles/utilities.css
  pnpm-lock.yaml
Labels: ui/ux, feature

#211 fix: gh-pages deployment
  packages/app/package.json
  packages/app/scripts/gh-pages-preview.sh
  packages/app/src/config.ts
  packages/app/src/pages/MintTokenPage.tsx
  packages/app/vite.config.ts
Labels: bug, config

#210 feat: add pools preview page
  .husky/pre-commit
  .lintstagedrc
  jest.config.ts
  package.json
  packages/app/package.json
  packages/app/src/App.tsx
  packages/app/src/AppRoutes.tsx
  packages/app/src/components/CoinInput.tsx
  packages/app/src/components/CoinSelector.tsx
  packages/app/src/components/PreviewTable.tsx
  packages/app/src/components/Spinner.tsx
  packages/app/src/components/Toaster.tsx
  packages/app/src/components/TokenIcon.tsx
  packages/app/src/config.ts
  packages/app/src/context/AppContext.tsx
  packages/app/src/hooks/useAddLiquidity.ts
  packages/app/src/hooks/useAssets.ts
  packages/app/src/hooks/usePoolInfo.ts
  packages/app/src/hooks/useUserPositions.tsx
  packages/app/src/lib/CoinsMetadata.ts
  packages/app/src/lib/constants.ts
  packages/app/src/lib/queryClient.tsx
  packages/app/src/lib/utils.ts
  packages/app/src/main.tsx
  packages/app/src/pages/PoolPage/AddLiquidity.tsx
  packages/app/src/pages/PoolPage/PoolsPreview.test.tsx
  packages/app/src/pages/PoolPage/PoolsPreview.tsx
  packages/app/src/pages/PoolPage/index.tsx
  packages/app/src/pages/SwapPage/helpers.ts
  packages/app/src/pages/SwapPage/index.tsx
  packages/app/src/queryClient.ts
  packages/app/src/styles/components/accordion.css
  packages/app/src/styles/components/toast.css
  packages/app/src/styles/index.css
  packages/app/src/types/contracts/index.ts
  packages/app/src/types/index.ts
  packages/app/src/types/pages.ts
  packages/app/vite.config.ts
  packages/test-utils/package.json
  packages/test-utils/src/index.ts
  packages/test-utils/src/render.tsx
  packages/test-utils/tsup.config.js
  pnpm-lock.yaml
Labels: feature

#214 fix(PoolPage): improve add_liquidity contract
  contracts/exchange_abi/src/main.sw
  contracts/exchange_contract/src/main.sw
  packages/app/.env.production
  packages/app/src/config.ts
  packages/app/src/hooks/useAddLiquidity.ts
  packages/app/src/pages/PoolPage/AddLiquidity.tsx
  packages/app/src/pages/PoolPage/PoolsPreview.tsx
  packages/app/src/pages/PoolPage/RemoveLiquidity.tsx
  packages/app/src/pages/PoolPage/index.tsx
  packages/app/src/types/contracts/Exchange_contractAbi.d.ts
  packages/app/src/types/contracts/factories/Exchange_contractAbi__factory.ts
Labels: bug, enhancement, priority:urgent

#218 feat: add Preview + Current Position to remove liquidity + some refacts
  packages/app/src/AppRoutes.tsx
  packages/app/src/components/CoinSelector.tsx
  packages/app/src/hooks/useCoinMetadata.ts
  packages/app/src/hooks/usePreviewLiquidity.ts
  packages/app/src/hooks/useUserPositions.tsx
  packages/app/src/lib/CoinsMetadata.ts
  packages/app/src/lib/asset.ts
  packages/app/src/lib/utils.ts
  packages/app/src/pages/PoolPage/AddLiquidity.tsx
  packages/app/src/pages/PoolPage/AddLiquidityPreview.tsx
  packages/app/src/pages/PoolPage/PoolCurrentPosition.tsx
  packages/app/src/pages/PoolPage/Pools.test.tsx
  packages/app/src/pages/PoolPage/Pools.tsx
  packages/app/src/pages/PoolPage/RemoveLiquidity.tsx
  packages/app/src/pages/PoolPage/RemoveLiquidityPreview.tsx
  packages/app/src/pages/PoolPage/usePreviewAddLiquidity.ts
  packages/app/src/pages/PoolPage/usePreviewRemoveLiquidity.ts
  packages/app/src/pages/SwapPage/PricePerToken.tsx
Labels: enhancement, page:pools, priority:urgent, page:rm_liquidity

#191 docs: Add `CONTRIBUTING` and `README`
  CONTRIBUTING.md
  README.md
  packages/app/README.md
Labels: documentation

#221 feat(AddLiquidityPage): add preview + current pool reserves
  packages/app/src/hooks/useEthBalance.ts
  packages/app/src/hooks/useUserPositions.tsx
  packages/app/src/lib/utils.ts
  packages/app/src/pages/PoolPage/AddLiquidity.tsx
  packages/app/src/pages/PoolPage/AddLiquidityPoolPrice.tsx
  packages/app/src/pages/PoolPage/AddLiquidityPreview.tsx
  packages/app/src/pages/PoolPage/PoolCurrentPosition.tsx
  packages/app/src/pages/PoolPage/PoolCurrentReserves.tsx
  packages/app/src/pages/PoolPage/Pools.tsx
  packages/app/src/pages/PoolPage/RemoveLiquidityPreview.tsx
  packages/app/src/pages/PoolPage/usePreviewAddLiquidity.ts
  packages/app/src/pages/PoolPage/usePreviewRemoveLiquidity.ts
Labels: enhancement, page:pools, priority:high

#228 refactor: add faucet popover when user is new
  packages/app/package.json
  packages/app/src/components/Button.tsx
  packages/app/src/components/CoinSelector.tsx
  packages/app/src/components/FaucetWidget.tsx
  packages/app/src/components/Popover.tsx
  packages/app/src/components/Tooltip.tsx
  packages/app/src/components/WalletWidget.tsx
  packages/app/src/pages/PoolPage/AddLiquidity.tsx
  packages/app/src/pages/PoolPage/RemoveLiquidity.tsx
  packages/app/src/styles/components/button.css
  packages/app/src/styles/components/coin-selector.css
  packages/app/src/styles/components/faucet-widget.css
  packages/app/src/styles/components/popover.css
  packages/app/src/styles/components/tooltip.css
  packages/app/src/styles/index.css
  pnpm-lock.yaml
Labels: enhancement, ui/ux

#230 feat: UX fixes
  packages/app/src/components/Card.tsx
  packages/app/src/components/NavigateBackButton.tsx
  packages/app/src/hooks/useAddLiquidity.ts
  packages/app/src/pages/PoolPage/AddLiquidity.tsx
  packages/app/src/pages/PoolPage/AddLiquidityPreview.tsx
  packages/app/src/pages/PoolPage/Pools.tsx
  packages/app/src/pages/PoolPage/RemoveLiquidity.tsx
  packages/app/src/styles/components/button.css
  packages/app/src/styles/components/layout.css
Labels: ui/ux, priority:urgent
