Repository FuelLabs/swayswap, pull requests merged in 2022-06, with the labels that each got.

#242 feat: new welcome screen
  .vscode/extensions.json
  CONTRIBUTING.md
  packages/app/package.json
  packages/app/public/illustrations/add-funds.png
  packages/app/public/illustrations/create-wallet.png
  packages/app/public/illustrations/done.png
  packages/app/src/AppRoutes.tsx
  packages/app/src/components/AnimatedPage.tsx
  packages/app/src/components/FaucetApp.tsx
  packages/app/src/components/FaucetWidget.tsx
  packages/app/src/components/Providers.tsx
  packages/app/src/components/RequireWallet.tsx
  packages/app/src/hooks/useCaptcha.ts
  packages/app/src/hooks/useFaucet.ts
  packages/app/src/hooks/useUserInfo.ts
  packages/app/src/hooks/useWelcomeSteps.tsx
  packages/app/src/layouts/MainLayout.tsx
  packages/app/src/pages/CreateWallet.tsx
  packages/app/src/pages/MintTokenPage.tsx
  packages/app/src/pages/SwapPage/SwapComponent.tsx
  packages/app/src/pages/WelcomePage/AddFunds.tsx
  packages/app/src/pages/WelcomePage/CreateWallet.tsx
  packages/app/src/pages/WelcomePage/StepsIndicator.tsx
  packages/app/src/pages/WelcomePage/WelcomeDone.tsx
  packages/app/src/pages/WelcomePage/WelcomeNavItem.tsx
  packages/app/src/pages/WelcomePage/WelcomePage.tsx
  packages/app/src/pages/WelcomePage/WelcomeSidebar.tsx
  packages/app/src/pages/WelcomePage/WelcomeSidebarBullet.tsx
  packages/app/src/pages/WelcomePage/WelcomeStep.tsx
  packages/app/src/pages/WelcomePage/index.tsx
  packages/app/src/styles/components/button.css
  packages/app/src/styles/components/faucet-widget.css
  packages/app/src/styles/components/main-layout.css
  packages/app/src/styles/components/welcome-page.css
  packages/app/src/styles/index.css
  packages/app/src/types/pages.ts
  packages/app/src/types/queries.ts
  pnpm-lock.yaml
Labels: feature

#263 refactor: cleanup docker infra and setup
  .github/workflows/pr.yaml
  .gitignore
  docker/.env
  docker/.env.test
  docker/Makefile
  docker/README.md
  docker/docker-compose.test.yml
  docker/docker-compose.yml
  docker/fuel-core/.env.docker
  docker/fuel-core/Dockerfile
  docker/fuel-core/start.sh
  docker/fuel-faucet/.env.docker
  package.json
  packages/app/.env.test
  packages/app/jest.config.ts
  packages/app/load.envs.ts
  packages/app/src/env.test.ts
  packages/app/vite.config.ts
  swayswap.config.ts
Labels: config

#266 docs: update docs with better visuals and guides
  README.md
  docker/README.md
  docker/docker-compose.yml
  docs/CONTRIBUTE_GUIDE.md
  docs/GETTING_STARTED.md
  docs/assets/launch-button.png
  docs/assets/preview-pages.gif
  package.json
  packages/app/README.md
  packages/contracts/README.md
Labels: documentation

#260 feat: add tests to wallet page + pool page
  .github/workflows/pr.yaml
  jest.config.ts
  package.json
  packages/app/.env.test
  packages/app/jest.config.ts
  packages/app/jest.sequence.js
  packages/app/load.envs.ts
  packages/app/package.json
  packages/app/src/App.test.tsx
  packages/app/src/env.test.ts
  packages/app/src/systems/Core/__tests__/mocks.ts
  packages/app/src/systems/Core/__tests__/utils.ts
  packages/app/src/systems/Core/components/Providers.tsx
  packages/app/src/systems/Core/components/WalletWidget.tsx
  packages/app/src/systems/Core/utils/constants.ts
  packages/app/src/systems/Faucet/hooks/useFaucet.ts
  packages/app/src/systems/Pool/__tests__/mocks.ts
  packages/app/src/systems/Pool/__tests__/tests.tsx
  packages/app/src/systems/Pool/hooks/useAddLiquidity.ts
  packages/app/src/systems/Pool/hooks/useUserPositions.ts
  packages/app/src/systems/Pool/pages/AddLiquidity.tsx
  packages/app/src/systems/Pool/pages/PoolPage.test.tsx
  packages/app/src/systems/Pool/pages/Pools.tsx
  packages/app/src/systems/Welcome/__tests__/tests.tsx
  packages/app/src/systems/Welcome/components/CreateWallet.tsx
  packages/app/src/systems/Welcome/components/WelcomePage.test.tsx
  packages/app/src/systems/Welcome/hooks/useWelcomeSteps.tsx
  packages/config/eslint.js
  packages/test-utils/src/mocks/localstorage.ts
  pnpm-lock.yaml
Labels: page:pools, page:wallet, tests

#262 fix: general ui issues
  jest.config.ts
  package.json
  packages/app/package.json
  packages/app/src/App.test.tsx
  packages/app/src/styles/components/button.css
  packages/app/src/styles/components/main-layout.css
  packages/app/src/styles/components/welcome-page.css
  packages/app/src/systems/Core/components/CoinSelector.tsx
  packages/app/src/systems/Core/hooks/useBalances.ts
  packages/app/src/systems/Core/hooks/useEthBalance.ts
  packages/app/src/systems/Faucet/hooks/useFaucet.ts
  packages/app/src/systems/Mint/hooks/useMint.ts
  packages/app/src/systems/Pool/__tests__/tests.tsx
  packages/app/src/systems/Pool/components/PoolCurrentPosition.tsx
  packages/app/src/systems/Pool/hooks/useAddLiquidity.ts
  packages/app/src/systems/Pool/hooks/usePreviewAddLiquidity.ts
  packages/app/src/systems/Pool/pages/AddLiquidity.tsx
  packages/app/src/systems/Pool/pages/PoolPage.test.tsx
  packages/app/src/systems/Pool/pages/Pools.tsx
  packages/app/src/systems/Pool/pages/RemoveLiquidity.tsx
  packages/app/src/systems/Swap/components/SwapPreview.tsx
  packages/app/src/systems/Swap/pages/SwapPage.tsx
  packages/app/src/systems/Swap/utils/helpers.ts
  packages/app/src/systems/Welcome/__tests__/tests.tsx
  packages/app/src/systems/Welcome/components/WelcomePage.test.tsx
  packages/app/src/types/contracts/ExchangeContractAbi.d.ts
  packages/app/src/types/contracts/TokenContractAbi.d.ts
  packages/config/package.json
  packages/scripts/package.json
  packages/test-utils/package.json
  packages/test-utils/tsup.config.js
  pnpm-lock.yaml
Labels: bug, ui/ux

#272 fix: swap error
  packages/app/src/systems/Swap/pages/SwapPage.tsx
  packages/app/src/systems/Swap/utils/helpers.ts
Labels: bug

#277 fix: gh preview
  packages/app/package.json
  packages/app/public/illustrations/add-funds.png
  packages/app/public/illustrations/create-wallet.png
  packages/app/public/illustrations/done.png
  packages/app/scripts/gh-pages-preview.sh
  packages/app/src/assets/fuel-logo-192x192.png
  packages/app/src/assets/fuel-logo-512x512.png
  packages/app/src/systems/Core/components/Header.tsx
  packages/app/src/systems/Core/utils/helpers.ts
  packages/app/src/systems/Welcome/components/AddFunds.tsx
  packages/app/src/systems/Welcome/components/CreateWallet.tsx
  packages/app/src/systems/Welcome/components/WelcomeDone.tsx
  packages/app/src/systems/Welcome/components/WelcomeSidebar.tsx
  packages/app/vite.config.ts
  pnpm-lock.yaml
Labels: bug

#268 feat: add gas fee calculation, preview and checks
  .github/workflows/pr.yaml
  .gitignore
  docker/.env
  docker/.env.test
  docker/README.md
  docker/docker-compose.yml
  docker/fuel-core/Dockerfile
  packages/app/package.json
  packages/app/scripts/postinstall.sh
  packages/app/src/config.ts
  packages/app/src/systems/Core/components/CoinInput.tsx
  packages/app/src/systems/Core/components/CoinSelector.tsx
  packages/app/src/systems/Core/components/NetworkFeePreviewItem.tsx
  packages/app/src/systems/Core/components/index.tsx
  packages/app/src/systems/Core/hooks/useTokensMethods.ts
  packages/app/src/systems/Core/hooks/useTransactionCost.ts
  packages/app/src/systems/Core/utils/gas.ts
  packages/app/src/systems/Faucet/components/FaucetWidget.tsx
  packages/app/src/systems/Mint/hooks/__mocks__/useMint.ts
  packages/app/src/systems/Mint/hooks/useMint.ts
  packages/app/src/systems/Mint/pages/MintPage.tsx
  packages/app/src/systems/Pool/components/AddLiquidityPreview.tsx
  packages/app/src/systems/Pool/components/RemoveLiquidityPreview.tsx
  packages/app/src/systems/Pool/hooks/__mocks__/useAddLiquidity.ts
  packages/app/src/systems/Pool/hooks/useAddLiquidity.ts
  packages/app/src/systems/Pool/pages/AddLiquidity.tsx
  packages/app/src/systems/Pool/pages/RemoveLiquidity.tsx
  packages/app/src/systems/Pool/utils/index.ts
  packages/app/src/systems/Pool/utils/queries.ts
  packages/app/src/systems/Swap/components/SwapComponent.tsx
  packages/app/src/systems/Swap/components/SwapPreview.tsx
  packages/app/src/systems/Swap/pages/SwapPage.test.tsx
  packages/app/src/systems/Swap/pages/SwapPage.tsx
  packages/app/src/systems/Swap/types.ts
  packages/app/src/systems/Swap/utils/helpers.ts
  packages/app/src/systems/Swap/utils/queries.ts
  packages/app/src/types/contracts/ExchangeContractAbi.d.ts
  packages/app/src/types/contracts/TokenContractAbi.d.ts
  packages/app/src/types/contracts/factories/TokenContractAbi__factory.ts
  packages/contracts/exchange_contract/src/main.sw
  packages/contracts/token_abi/src/main.sw
  packages/contracts/token_contract/src/main.sw
  packages/contracts/token_contract/tests/harness.rs
  packages/scripts/README.md
  packages/scripts/package.json
  packages/scripts/src/actions/deployContractBinary.ts
  packages/scripts/src/bin/bin.ts
  packages/scripts/src/bin/index.ts
  packages/scripts/src/types.ts
  packages/test-utils/setup.ts
  pnpm-lock.yaml
  scripts/ci-test.sh
  scripts/create-test-env.sh
  scripts/test-contracts.sh
Labels: feature

#280 feat: add landing page as index
  packages/app/cypress/e2e/App.cy.ts
  packages/app/package.json
  packages/app/public/lp-bg.jpg
  packages/app/src/App.css
  packages/app/src/main.tsx
  packages/app/src/routes.tsx
  packages/app/src/styles/components/home-page.css
  packages/app/src/styles/index.css
  packages/app/src/systems/Core/components/MainLayout.tsx
  packages/app/src/systems/Core/components/PrivateRoute.tsx
  packages/app/src/systems/Core/components/Providers.tsx
  packages/app/src/systems/Core/components/index.tsx
  packages/app/src/systems/Home/components/Header.tsx
  packages/app/src/systems/Home/components/HomeHero.tsx
  packages/app/src/systems/Home/index.tsx
  packages/app/src/systems/Home/pages/HomePage.tsx
  packages/app/src/systems/Home/pages/index.tsx
  packages/app/src/systems/Home/routes.tsx
  packages/app/src/systems/Mint/pages/MintPage.tsx
  packages/app/src/systems/Mint/routes.tsx
  packages/app/src/systems/Pool/pages/PoolPage.tsx
  packages/app/src/systems/Pool/routes.tsx
  packages/app/src/systems/Swap/pages/SwapPage.test.tsx
  packages/app/src/systems/Swap/pages/SwapPage.tsx
  packages/app/src/systems/Swap/routes.tsx
  packages/app/src/systems/Welcome/routes.tsx
  packages/app/src/types/index.ts
  packages/app/tailwind.config.js
  packages/test-utils/config.ts
  pnpm-lock.yaml
Labels: feature

#300 fix: reduce images on mobile
  packages/app/src/styles/components/welcome-page.css
Labels: bug, ui/ux

#296 chore: Add storage annotations to contracts.
  .github/workflows/deploy-contracts.yml
  .github/workflows/pr.yaml
  packages/app/.env.production
  packages/contracts/exchange_abi/src/main.sw
  packages/contracts/exchange_contract/src/main.sw
  packages/contracts/token_abi/src/main.sw
  packages/contracts/token_contract/src/main.sw
Labels: contracts

#301 chore: clean up readme and docs.
  README.md
  docs/CONTRIBUTING.md
  docs/GETTING_STARTED.md
Labels: documentation

#304 chore: add legal disclaimer
  docs/LEGAL_DISCLAIMER.md
Labels: documentation

#299 feat: add twitter dialog after swap
  packages/app/cypress/e2e/App.cy.ts
  packages/app/src/systems/Swap/pages/SwapPage.tsx
  packages/app/src/systems/Tweet/components/TwitterDialog.tsx
  packages/app/src/systems/Tweet/hooks/useTwitterDialog.ts
  packages/app/src/systems/Tweet/index.ts
  packages/app/src/systems/UI/components/Link.tsx
Labels: enhancement

#308 feat: add block explorer links on swap feedback and wallet info
  .npmrc
  package.json
  packages/app/package.json
  packages/app/src/config.ts
  packages/app/src/styles/components/button.css
  packages/app/src/styles/components/coin-input.css
  packages/app/src/styles/components/header.css
  packages/app/src/styles/components/input.css
  packages/app/src/styles/components/main-layout.css
  packages/app/src/styles/components/toast.css
  packages/app/src/styles/components/tooltip.css
  packages/app/src/styles/utilities.css
  packages/app/src/systems/Core/components/CoinsListDialog.tsx
  packages/app/src/systems/Core/components/WalletInfo.tsx
  packages/app/src/systems/Core/hooks/useTokensMethods.ts
  packages/app/src/systems/Core/hooks/useTransactionCost.ts
  packages/app/src/systems/Core/utils/feedback.tsx
  packages/app/src/systems/Core/utils/gas.ts
  packages/app/src/systems/Core/utils/queryClient.tsx
  packages/app/src/systems/Mint/hooks/useMint.ts
  packages/app/src/systems/Pool/components/AddLiquidityPoolPrice.tsx
  packages/app/src/systems/Pool/pages/AddLiquidity.tsx
  packages/app/src/systems/Swap/pages/SwapPage.test.tsx
  packages/app/src/systems/Swap/pages/SwapPage.tsx
  packages/app/src/systems/Swap/utils/queries.ts
  packages/app/src/systems/UI/components/InvertButton.tsx
  packages/app/src/systems/UI/components/NumberInput.tsx
  packages/app/src/types/contracts/ExchangeContractAbi.d.ts
  packages/app/src/types/contracts/TokenContractAbi.d.ts
  packages/app/vite.config.ts
  packages/config/package.json
  packages/scripts/package.json
  packages/test-utils/package.json
  pnpm-lock.yaml
  scripts/update-deps.sh
Labels: feature

#313 style: bump tx feedback 5s -> 8s
  packages/app/src/systems/Core/utils/feedback.tsx
Labels: ui/ux, page:swap

#321 refactor: share button link direct to twitter
  packages/app/src/styles/components/actions-widget.css
  packages/app/src/systems/Core/components/ActionsWidget.tsx
  packages/app/src/systems/Tweet/components/TwitterDialog.tsx
  packages/app/src/systems/Tweet/hooks/useTwitterDialog.ts
  packages/app/src/systems/Tweet/index.ts
Labels: enhancement

#324 chore: remove redundant docs link in header
  packages/app/src/systems/Home/components/Header.tsx
Labels: ui/ux

#325 chore: remove launch app button on home
  packages/app/src/systems/Home/components/HomeHero.tsx
Labels: ui/ux

#330 chore: Revert "chore: remove launch app button on home"
  packages/app/src/systems/Home/components/HomeHero.tsx
Labels: ui/ux, priority:urgent

#335 feat: loading button size
  packages/app/src/systems/UI/components/Button.tsx
Labels: enhancement

#336 feat: avoid multiple error notifications
  packages/app/src/systems/Core/utils/queryClient.tsx
Labels: enhancement

#352 feat: make tests run in parallel
  .github/setup-docker/action.yml
  .github/setup-node/action.yml
  .github/setup-rust/action.yml
  .github/workflows/deploy-contracts.yml
  .github/workflows/gh-pages.yml
  .github/workflows/pr.yaml
Labels: enhancement, tests
